CREATE TABLE `paid-project-346208`.car_ads_ds_staging_test.`cars_com_card_tokenized_300_Dima` 
(
	row_id STRING,
	card_id STRING NOT NULL,
	brand STRING,
	model STRING,
	`year` INT64,
	price_history STRING,
	price_usd NUMERIC,
	adress STRING,
	state STRING,
	zip_code STRING,
	home_delivery STRING,
	virtual_appointments STRING,
	included_warranty STRING,
	VIN STRING,
	transmission STRING,
	transmission_type STRING,
	engine STRING,
	engine_vol NUMERIC,
	fuel STRING,
	mpg STRING,
	mileage INT64,
	mileage_unit STRING,
	body STRING,
	drive STRING,
	color STRING,
	one_owner STRING,
	accidents_or_damage STRING,
	clean_title STRING,
	personal_use_only STRING,
	comment STRING,
	scrap_date TIMESTAMP,
	source_id STRING,
	modified_date TIMESTAMP,
	row_hash BYTES,	
	operation STRING
);